config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :instances do
    member do
      post :start
      post :close
      post :add_game
      post :remove_game
      post :update_frame
      post :calculate
    end
  end

  root 'home#index'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :slot
  has_many :games

  NEW = 10
  STARTED = 20
  CLOSED = 30
  STATE_NAME_LIST= {NEW => 'instance_state_new', STARTED => 'instance_state_started', CLOSED => 'instance_state_closed'}

  validates :name, presence: true, length: { minimum: 3, maximum: 32}, :uniqueness => { :scope => :slot_id, :case_sensitive => false }, :if => Proc.new { |m| m.name_changed? }
  validates_numericality_of :current_frame, :greater_than_or_equal_to => 0, :allow_nil => false
  validates_numericality_of :current_game, :greater_than_or_equal_to => 0, :allow_nil => false
  validates :slot_id, :uniqueness => { scope: [:finalized, :state_id], :case_sensitive => false }, :if => Proc.new { |m| m.state_id_changed? }

  validate :post_validate
  delegate :name, :to => :slot, :prefix => true

  def post_validate
    errors.add :base, I18n.t('errors.instance_already_closed') if self.closed?
  end

  def closed?
    self.state_id == CLOSED && self.state_id_was == CLOSED
  end

  def state_name
    I18n.t(STATE_NAME_LIST[self.state_id])
  end

  def calculate
    return false unless check_close

    frame_list= []
    self.games.each do |g|
      frame_list<< g.calculate(g.frames.order(:offset))
    end

    [frame_list, self.games].flatten
  end

  def check_start
    if self.state_id != NEW
      false
    else
      true
    end
  end

  def start
    unless self.check_start
      logger.error "ERROR: Instance#start, #{I18n.t('errors.instance_must_be_new')},#{self.inspect}"
      return false
    end

    if self.games.size == 0
      errors.add :base, I18n.t('errors.instance_can_not_start_without_player')
      return false
    end

    self.state_id = STARTED
    
    self.current_game= 1
    self.current_frame= 0
    true
  end

  def check_close
    if self.state_id != STARTED
      false
    else
      true
    end
  end

  def close
    return false unless check_close

    frames = []
    begin
      games.each do |game|
        frames << game.calculate
        logger.debug "DEBUG: Instance#close, Calculation completed for #{game.inspect}"
      end
    rescue Exception => ex
      logger.error "ERROR: Instance#close, #{ex}, #{self.inspect}"
      return false
    end
    
    self.state_id = CLOSED
    self.finalized = self.id

    (frames + games).flatten
  end

  def update_frame(throw1, throw2, throw3)
    if self.current_game == 0
      self.current_frame+= 0
      self.current_game+= 1
      return false
    end
    
    game= self.games.select { |g| g.offset == self.current_game }[0]
    frame= game.frames.select { |f| f.offset == self.current_frame }[0]

    frame.throw1= throw1
    frame.throw2= throw2
    frame.throw3= throw3

    if self.current_frame >= Game::MAX_FRAME_OFFSET
      next_games= self.games.order(:offset).select { |g| g.offset > self.current_game }
      if next_games.size != 0
        self.current_game= next_games[0].offset
      else
        self.current_game= 1
      end
      self.current_frame= 0
    else
      self.current_frame+= 1
    end
    [game, frame]
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :close, :start, :add_game, :remove_game, :update_frame, :calculate]

  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.all
  end

  def calculate
    result= false
    error_str= ''
    lock= LockMaster.lock('instances', @instance.id, 'instance.calculate')
    begin
      save_list= @instance.calculate
      Instance.transaction do
        begin
          if save_list
            save_list.each do |o|
              o.save!
            end
          end
          result= true
        rescue Exception => ex
          logger.error "ERROR: InstanceCNT#calculate, #{ex}, #{@instance.inspect}"
          result= false
          error_str= ex.message
        end
      end
    ensure
      lock.clear if lock != nil
    end

    respond_to do |format|
      if result
        format.html { redirect_to @instance, notice: t('instance_calculated') }
        format.json { render :show, status: :ok, location: @instance }
      else
        format.html { redirect_to @instance, alert: "#{t('errors.instance_not_calculated')} #{error_str}" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_frame
    throw1= params[:throw1]
    throw2= params[:throw2]
    throw3= params[:throw3]

    result= false
    error_str= ''
    lock= LockMaster.lock('instances', @instance.id, 'instance.update_frame')
    begin
      save_list= @instance.update_frame(throw1, throw2, throw3)
      Instance.transaction do
        begin
          if save_list
            save_list.each do |o|
              o.save!
            end
          end
          @instance.save!
          result= true
        rescue Exception => ex
          logger.error "ERROR: InstancesController#update_frame, #{ex}, #{@instance.inspect}"
          result= false
          error_str= ex.message
        end
      end
    ensure
      lock.clear if lock != nil
    end

    respond_to do |format|
      if result
        format.html { redirect_to @instance, notice: t('instance_frame_updated') }
        format.json { render :show, status: :ok, location: @instance }
      else
        format.html { redirect_to @instance, alert: "#{t('errors.instance_frame_not_updated')} #{error_str}" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_game
    game= Game.new()
    game.name= params[:name]
    if @instance.check_start == false
      redirect_to @instance, alert: t('errors.game_can_not_added_instance_started')
      return
    end

    lock= LockMaster.lock('instances', @instance.id, 'instance.add_game')
    begin
      game.offset= (@instance.games.maximum('offset')||0) + 1
    ensure
      lock.clear if lock != nil
    end
    @instance.games<< game

    respond_to do |format|
      if game.save
        format.html { redirect_to @instance, notice: "#{t('game_added')} (#{game.full_name})" }
        format.json { render :show, status: :created, location: game }
      else
        format.html { redirect_to @instance, alert: "#{t('errors.game_can_not_added')} #{game.errors.full_messages.join(',')}" }
        format.json { render json: game.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_game
    if @instance.check_close == false && @instance.check_start == false
      redirect_to @instance, alert: t('errors.game_can_not_removed_instance_closed')
      return
    end

    game_id= params[:game_id]
    result= @instance.games.destroy(Game.find(game_id))

    respond_to do |format|
      if result != nil
        format.html { redirect_to @instance, notice: "#{t('game_removed')} #{result[0].full_name}" }
        format.json { render :show, status: :deleted, location: game }
      else
        format.html { render :show, alert: t('errors.game_can_not_removed') }
        format.json { render json: game.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @games= @instance.games.order('offset, name')
    @frames= Frame.where('game_id in (?)', @games.collect { |g| g.id }.flatten)

    @current_game_name= @games.select { |g| g.offset == @instance.current_game }[0].try(:name)
  end

  # GET /instances/new
  def new
    @instance = Instance.new
    @instance.slot_id= params[:slot_id]
    @instance.state_id= Instance::NEW
  end

  # GET /instances/1/edit
  def edit
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(instance_params)
    @instance.state_id= Instance::NEW

    respond_to do |format|
      if @instance.save
        format.html { redirect_to @instance, notice: t('instance_created') }
        format.json { render :show, status: :created, location: @instance }
      else
        format.html { render :new }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instances/1
  # PATCH/PUT /instances/1.json
  def update
    respond_to do |format|
      if @instance.update(instance_params)
        format.html { redirect_to @instance, notice: t('instance_updated') }
        format.json { render :show, status: :ok, location: @instance }
      else
        format.html { render :edit }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  def start
    result= false
    lock= LockMaster.lock('instances', @instance.id, 'instance.start')
    begin
      result= @instance.save if @instance.start
    ensure
      lock.clear if lock != nil
    end

    respond_to do |format|
      if result
        format.html { redirect_to @instance, notice: t('instance_started') }
        format.json { render :show, status: :created, location: @instance }
      else
        format.html { redirect_to @instance, alert: "#{t('errors.instance_not_started')} #{@instance.errors.full_messages.join(',')}" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  def close
    result= false
    lock= LockMaster.lock('instances', @instance.id, 'instance.close')
    begin
      result= @instance.save! if @instance.close
    rescue Exception => ex
      logger.error "ERROR: InstancesController#close, #{ex}, #{@instance.inspect}"
    ensure
      lock.clear if lock != nil
    end

    respond_to do |format|
      if result
        format.html { redirect_to @instance, notice: t('instance_closed') }
        format.json { render :show, status: :created, location: @instance }
      else
        format.html { redirect_to @instance, alert: "#{t('errors.instance_not_closed')} #{@instance.errors.full_messages.join(',')}" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params.require(:instance).permit(:name, :slot_id, :current_game, :current_frame)
    end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<div class="table-title">
  <h3 class="title"><%= t('activerecord.models.instance') %></h3>
</div>
<div class="col-md-6">
  <%= simple_form_for @instance, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_box: :horizontal_radio_and_checkboxes,
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
    <%= f.error_notification %>
    <div class="has-error">
      <%= f.error :base %>
    </div>
    <%= f.input :slot_id, :as => :hidden %>
    <%= f.input :state_id, :as => :hidden %>
    <%= f.input :slot_name, disabled: true %>
    <%= f.input :name %>
    <%= f.input :state_name, disabled: true %>
    <%= f.input :current_frame %>
    <%= f.input :current_game %>
    <div class="form-group">
      <div class="col-sm-2"></div>
      <div class="col-sm-10">
        <%= f.button :submit, :class => "btn-success" %>  
        <% if action_name == 'new' %>
        <%= link_to 'Back', root_path %>
        <% else %>
        <%= link_to 'Back', @instance %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/instances/edit.html.erb
<%= render 'form' %>

app/views/instances/new.html.erb
<%= render 'form' %>

app/views/instances/show.html.erb
<div class="table-title">
  <h3 class="title"><%= t('activerecord.models.instance') %></h3>
</div>
<div class="row">
  <div class="col-md-12">
  <%= simple_form_for(@instance, legend: t('activerecord.models.instance'), html: {class: 'form-horizontal' }) do |f| %>
    <%= f.error_notification %>
    <dl class="inputs dl-horizontal">
      <dt><%= f.label :slot_name %>:</dt>
      <dd><%= @instance.slot_name %></dd>
      <dt><%= f.label :name %>:</dt>
      <dd><%= @instance.name %></dd>
      <dt><%= f.label :state_name %>:</dt>
      <dd><%= @instance.state_name %></dd>
      <dt><%= f.label :current_frame %>:</dt>
      <dd><%= @instance.current_frame %></dd>
      <dt><%= f.label :current_game %>:</dt>
      <dd><%= @instance.current_game %></dd>
    </dl>
  </div>
  <% end %>
</div>
<div class="row">  
  <div class="col-md-2"></div>
  <div class="col-md-10">
    <% if @instance.check_close || @instance.check_start %>
    <%= link_to 'Edit', edit_instance_path(@instance.id) %>
    <% end %>
    <%= link_to 'Back', root_path %>
  </div>
</div>
<div class="table-title">
  <h4 class="title"><%= t('activerecord.models.game').pluralize %></h4>
</div>
<div class="row">
<% if @instance.check_start %>
  <%= form_tag add_game_instance_path, :method => 'POST' do -%>
  <div class="btn-group top-left">
    <div class="btn-group">
      <%= label_tag :name %>
      <%= text_field_tag :name %>
    </div>
  </div>
  <button type="submit" class="btn btn-default"><%= t('actions.new') %></button>
  <% end -%>
<% end %>
<% if @instance.check_close %>
  <%= form_tag update_frame_instance_path, :method => 'POST' do -%>
  <div class="btn-group top-left">
    <div class="btn-group">
      <%= label_tag :throw1 %>: 
      <%= text_field_tag :throw1, params[:throw1], size: 3 %>
    </div>
    <div class="btn-group">
      <%= label_tag :throw2 %>: 
      <%= text_field_tag :throw2, params[:throw2], size: 3 %>
    </div>
    <% if @instance.current_frame == Game::MAX_FRAME_OFFSET %>
      <div class="btn-group">
        <%= label_tag :throw3 %>: 
        <%= text_field_tag :throw3, params[:throw3], size: 3 %>
      </div>
    <% end %>
  </div>
  <button type="submit" class="btn btn-default"><%= "#{t('actions.update_frame')} for #{@current_game_name}x#{@instance.current_frame}" %></button>
  <% end -%>
<% end %>
</div>
<div class="row">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('simple_form.labels.defaults.offset') %></th>
      <th><%= t('simple_form.labels.defaults.name') %></th>
      <th><%= t('simple_form.labels.defaults.score') %></th>
      <% 10.times do |i| %>
      <th style="text-align: right"><%= i %></th>
      <% end %>
      <th colspan="1">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |g| %>
      <tr>
        <td><%= g.offset %></td>
        <td><%= g.name %></td>
        <td><%= g.score %></td>
        <% @frames.select { |f| f.game_id == g.id }.each do |f| %>
          <% if f.offset == @instance.current_frame && g.offset == @instance.current_game %>
          <td style="text-align: right;background-color: pink">
          <% else %>
          <td style="text-align: right">
          <% end %>
          <% if f.offset == Game::MAX_FRAME_OFFSET %>
            <%= "#{f.throw1} / #{f.throw2||0} / #{f.throw3||0} = #{f.score}" %>
          <% else %>
            <%= "#{f.throw1} / #{f.throw2||0} = #{f.score}" %>
          <% end %>
          </td>
        <% end %>
        <td>
          <%= @instance.check_close == false ? ' ' : button_to(t('actions.delete'), remove_game_instance_path(:game_id => g.id)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <th colspan="14">&nbsp;</th>
  </tfoot>
</table>
</div>
<div class="row">
  <div class="btn-group top-left">
    <div class="btn-group">
      <% if @instance.check_start %>
        <%= button_to t('actions.start'), start_instance_path %>
      <% end %>
      <% if @instance.check_close %>
        <%= button_to t('actions.calculate'), calculate_instance_path %>
        <%= button_to t('actions.close'), close_instance_path %>
      <% end %>
    </div>
  </div>
</div>